// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZIKGqbjBBGSHByKIakOGKi1xHntdHsaw',
    appId: '1:1019893961708:web:fdea9f9a89f330f0f6a6c9',
    messagingSenderId: '1019893961708',
    projectId: 'premieres3',
    authDomain: 'premieres3.firebaseapp.com',
    storageBucket: 'premieres3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTFjMV4kwQBek5KX4G7vzl87gvI3yRoV8',
    appId: '1:1019893961708:android:27cbeb3ff8613af1f6a6c9',
    messagingSenderId: '1019893961708',
    projectId: 'premieres3',
    storageBucket: 'premieres3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWxM-4WNsyW_EDdJO4OkO0r3RTwn5KjqE',
    appId: '1:1019893961708:ios:26ecdb6f81de96d0f6a6c9',
    messagingSenderId: '1019893961708',
    projectId: 'premieres3',
    storageBucket: 'premieres3.appspot.com',
    iosClientId: '1019893961708-qal1179kptbq0jukmnnndpukdkcmgf94.apps.googleusercontent.com',
    iosBundleId: 'com.klaudiabak.premieres',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWxM-4WNsyW_EDdJO4OkO0r3RTwn5KjqE',
    appId: '1:1019893961708:ios:26ecdb6f81de96d0f6a6c9',
    messagingSenderId: '1019893961708',
    projectId: 'premieres3',
    storageBucket: 'premieres3.appspot.com',
    iosClientId: '1019893961708-qal1179kptbq0jukmnnndpukdkcmgf94.apps.googleusercontent.com',
    iosBundleId: 'com.klaudiabak.premieres',
  );
}
